baseURL = "https://my-blog-53c.pages.dev/"
languageCode = "zh-cn"
title = "小龙的学习笔记"
theme = "PaperMod"

[params]
  env = "production"
  description = "小龙的学习笔记"
  author = "小龙"

  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "👋 Hello，我是李小龙"
    Content = "一个喜欢折腾 IT 技术的人"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  identifier = "posts"
  name = "笔记"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 30